export { VsdxEditor } from './VsdxEditor';
export type { VsdxEditorApi, VsdxEditorCollaborationOptions, VsdxEditorProps, VsdxShapeSelection } from './VsdxEditor';
export { connectorTargetForPoint, nearestPointOnShape } from './VsdxEditor';
export { AUTO_CONNECT_FADE_MS, AUTO_CONNECT_GAP_PX, AUTO_CONNECT_HALO_PX, AUTO_CONNECT_HIT_PX, AUTO_CONNECT_SIDES, AUTO_CONNECT_SIZE_PX, CONNECTOR_GLUE_MATCH_INCHES, CONNECTOR_SNAP_INCHES, QUICK_SHAPE_GAP_INCHES, QUICK_SHAPE_IDS, arrowheadPolygon, autoConnectArrowAt, autoConnectArrowCenter, autoConnectArrowCss, autoConnectArrowsForShape, autoConnectHaloHit, autoConnectMetrics, classifyConnectorEndpoint, connectionPointsForShape, connectorDraft, connectorEndpointGlue, connectorGlue, connectorRouteFromFrame, dropTargetForPoint, formatInches, isConnectorShape, modelToPage, movedShapePoints, nearestConnectionPoint, nearestConnectionPointAnywhere, paintAutoConnectOverlay, paintConnectorEndpoint, paintConnectorOverlay, quickShapePlacement, reroutePreviewForMove, routeConnector } from './connector';
export type { AutoConnectArrow, AutoConnectOverlayState, AutoConnectSide, ConnectionPoint, ConnectorDragEndpoint, ConnectorEndpointGlue, ConnectorOverlayRoute, ConnectorOverlayScene, ConnectorSide, MovedShapeGeometry, QuickShapePlacement } from './connector';
export { Ribbon } from './components/ribbon/Ribbon';
export type { RibbonConnectorToggle } from './components/ribbon/Ribbon';
export { CommandMenu, CommandMenuItem } from './components/ribbon/CommandMenu';
export type { CommandMenuEntry } from './components/ribbon/CommandMenu';
export { ShapeContextMenu } from './components/ribbon/ShapeContextMenu';
export type { ShapeContextMenuProps } from './components/ribbon/ShapeContextMenu';
export { MINI_TOOLBAR_CANDIDATES, ShapeMiniToolbar, miniToolbarPosition, resolveMiniToolbarIds } from './components/ribbon/ShapeMiniToolbar';
export type { MiniToolbarRect, MiniToolbarSize, MiniToolbarViewport, ShapeMiniToolbarProps } from './components/ribbon/ShapeMiniToolbar';
export { CanvasContextMenu } from './components/ribbon/CanvasContextMenu';
export type { CanvasContextMenuProps } from './components/ribbon/CanvasContextMenu';
export { RibbonIcon } from './components/ribbon/RibbonIcon';
export type { RibbonIconName } from './components/ribbon/RibbonIcon';
export { RibbonCommandsContext, RibbonCommandsProvider, addShapeWithText, copySelection, createRibbonCommands, duplicateEntry, GATED_CELLS, findShapePlacement, isCellWriteBlocked, isDeleteBlocked, isHandleResizeBlocked, isRotateBlocked, pasteEntry, probeKey, selectionWriteProbes, shapeWriteProbes, useRibbonCommands } from './components/ribbon/commands';
export type { ShapeWriteProbes } from './components/ribbon/commands';
export type { RibbonCommand, RibbonCommandId, RibbonCommands, RibbonCommandsProviderProps, ShapePlacement } from './components/ribbon/commands';
export { DUPLICATE_OFFSET, PASTE_OFFSET, buildClipboardEntry, canCopyShape, copyRefusalReason, draftForPaste, draftTreeForPaste, isTreeEntry, resolvedNumeric, toFormula } from './components/ribbon/clipboard';
export type { VsdxClipboardEntry, VsdxClipboardGlue } from './components/ribbon/clipboard';
export { ShapesPanel } from './components/shapes/ShapesPanel';
export type { ShapesPanelProps } from './components/shapes/ShapesPanel';
export { ShapeDataPanel } from './components/shapeData/ShapeDataPanel';
export type { ShapeDataPanelProps } from './components/shapeData/ShapeDataPanel';
export { LayersPanel } from './components/layers/LayersPanel';
export type { LayersPanelProps } from './components/layers/LayersPanel';
export { IssuesPanel, issueMessage } from './components/issues/IssuesPanel';
export type { IssuesPanelProps } from './components/issues/IssuesPanel';
export { DrawingExplorer, MAX_EXPLORER_DEPTH, findShapePath, groupSectionRows, groupShapeSections, isOneDimensional } from './components/explorer';
export type { DrawingExplorerProps, ExplorerRow, ExplorerSection } from './components/explorer';
export { arrowShapes, shapeLabel, shapeStencils, standardShapeById, standardShapes, stencilShapeById } from './components/shapes/shapeLibrary';
export type { ShapeStencil, StandardShape } from './components/shapes/shapeLibrary';
export { documentMasterDraft, documentStencilEntries, masterPreviewPath } from './components/shapes/documentStencil';
export { MAX_ZOOM, MIN_ZOOM, StatusBar, ZOOM_STOPS, clampZoom, sliderPositionForZoom, zoomForSliderPosition } from './components/statusbar';
export type { StatusBarPage, StatusBarProps } from './components/statusbar';
